language: r
cache: packages
r:
  - release
  - devel

language: r
latex: false
fortran: false

matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: osx
      r: release
    - os: osx
      r: devel